apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zookeeper.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    {{- include "dubbo-mesh.zookeeper-service.selectorLabels" . | nindent 4 }}
  ports:
  - name: zk
    port: {{ .Values.zookeeper.service.port }}
    protocol: TCP
    targetPort: zk
